export type Quote = {
  text: string;
  author: string;
};

// A curated, offline-first collection of quotes. The app ships these with the
// bundle so it works with no network connection. The daily selection logic in
// `getDailyQuote` rotates deterministically through this list, so every user
// sees the same quote on a given calendar day and a different one each day.
export const quotes: Quote[] = [
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Whether you think you can or you think you can’t, you’re right.', author: 'Henry Ford' },
  { text: 'Life is what happens when you’re busy making other plans.', author: 'John Lennon' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Everything you’ve ever wanted is on the other side of fear.', author: 'George Addair' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'Hardships often prepare ordinary people for an extraordinary destiny.', author: 'C.S. Lewis' },
  { text: 'Believe you can and you’re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'The mind is everything. What you think you become.', author: 'Buddha' },
  { text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese Proverb' },
  { text: 'An unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Your time is limited, so don’t waste it living someone else’s life.', author: 'Steve Jobs' },
  { text: 'If life were predictable it would cease to be life, and be without flavor.', author: 'Eleanor Roosevelt' },
  { text: 'If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success.', author: 'James Cameron' },
  { text: 'Life is what we make it, always has been, always will be.', author: 'Grandma Moses' },
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: 'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.', author: 'Winston Churchill' },
  { text: 'Don’t let yesterday take up too much of today.', author: 'Will Rogers' },
  { text: 'You learn more from failure than from success. Don’t let it stop you. Failure builds character.', author: 'Unknown' },
  { text: 'It’s not whether you get knocked down, it’s whether you get up.', author: 'Vince Lombardi' },
  { text: 'If you are working on something exciting that you really care about, you don’t have to be pushed.', author: 'Steve Jobs' },
  { text: 'People who are crazy enough to think they can change the world are the ones who do.', author: 'Rob Siltanen' },
  { text: 'Failure will never overtake me if my determination to succeed is strong enough.', author: 'Og Mandino' },
  { text: 'We may encounter many defeats but we must not be defeated.', author: 'Maya Angelou' },
  { text: 'Knowing is not enough; we must apply. Wishing is not enough; we must do.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Imagine your life is perfect in every respect; what would it look like?', author: 'Brian Tracy' },
  { text: 'We generate fears while we sit. We overcome them by action.', author: 'Dr. Henry Link' },
  { text: 'Whatever the mind of man can conceive and believe, it can achieve.', author: 'Napoleon Hill' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'To see what is right and not to do it is a lack of courage.', author: 'Confucius' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'The only limit to our realization of tomorrow will be our doubts of today.', author: 'Franklin D. Roosevelt' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'When you reach the end of your rope, tie a knot in it and hang on.', author: 'Franklin D. Roosevelt' },
  { text: 'Always remember that you are absolutely unique. Just like everyone else.', author: 'Margaret Mead' },
  { text: 'Don’t judge each day by the harvest you reap but by the seeds that you plant.', author: 'Robert Louis Stevenson' },
  { text: 'The future belongs to those who prepare for it today.', author: 'Malcolm X' },
  { text: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', author: 'Benjamin Franklin' },
  { text: 'The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.', author: 'Helen Keller' },
  { text: 'It is during our darkest moments that we must focus to see the light.', author: 'Aristotle' },
  { text: 'Whoever is happy will make others happy too.', author: 'Anne Frank' },
  { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
  { text: 'You will face many defeats in life, but never let yourself be defeated.', author: 'Maya Angelou' },
  { text: 'In the end, it’s not the years in your life that count. It’s the life in your years.', author: 'Abraham Lincoln' },
  { text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth' },
  { text: 'Life is either a daring adventure or nothing at all.', author: 'Helen Keller' },
  { text: 'Many of life’s failures are people who did not realize how close they were to success when they gave up.', author: 'Thomas A. Edison' },
  { text: 'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.', author: 'Dr. Seuss' },
  { text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein' },
  { text: 'The person who says it cannot be done should not interrupt the person who is doing it.', author: 'Chinese Proverb' },
  { text: 'There are no traffic jams along the extra mile.', author: 'Roger Staubach' },
  { text: 'It is never too late to be what you might have been.', author: 'George Eliot' },
  { text: 'You become what you believe.', author: 'Oprah Winfrey' },
  { text: 'I would rather die of passion than of boredom.', author: 'Vincent van Gogh' },
  { text: 'A truly rich man is one whose children run into his arms when his hands are empty.', author: 'Unknown' },
  { text: 'If you want to lift yourself up, lift up someone else.', author: 'Booker T. Washington' },
  { text: 'You can’t use up creativity. The more you use, the more you have.', author: 'Maya Angelou' },
  { text: 'Dream big and dare to fail.', author: 'Norman Vaughan' },
  { text: 'Our lives begin to end the day we become silent about things that matter.', author: 'Martin Luther King Jr.' },
  { text: 'Do what you feel in your heart to be right, for you’ll be criticized anyway.', author: 'Eleanor Roosevelt' },
  { text: 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', author: 'Anne Frank' },
  { text: 'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.', author: 'Henry Ford' },
  { text: 'It’s not the years in your life that count. It’s the life in your years.', author: 'Abraham Lincoln' },
  { text: 'Change your thoughts and you change your world.', author: 'Norman Vincent Peale' },
  { text: 'Either write something worth reading or do something worth writing.', author: 'Benjamin Franklin' },
  { text: 'Nothing is impossible, the word itself says “I’m possible”!', author: 'Audrey Hepburn' },
  { text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
  { text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau' },
  { text: 'When I let go of what I am, I become what I might be.', author: 'Lao Tzu' },
  { text: 'Life is not measured by the number of breaths we take, but by the moments that take our breath away.', author: 'Maya Angelou' },
  { text: 'Happiness is not something readymade. It comes from your own actions.', author: 'Dalai Lama' },
  { text: 'If you can dream it, you can achieve it.', author: 'Zig Ziglar' },
  { text: 'The harder I work, the luckier I get.', author: 'Samuel Goldwyn' },
  { text: 'Try not to become a man of success. Rather become a man of value.', author: 'Albert Einstein' },
  { text: 'I have not failed. I’ve just found 10,000 ways that won’t work.', author: 'Thomas A. Edison' },
  { text: 'A goal is a dream with a deadline.', author: 'Napoleon Hill' },
  { text: 'It always seems impossible until it’s done.', author: 'Nelson Mandela' },
  { text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
  { text: 'The way I see it, if you want the rainbow, you gotta put up with the rain.', author: 'Dolly Parton' },
  { text: 'You miss 100% of the shots you don’t take.', author: 'Wayne Gretzky' },
  { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln' },
  { text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain' },
  { text: 'A room without books is like a body without a soul.', author: 'Marcus Tullius Cicero' },
  { text: 'Be yourself; everyone else is already taken.', author: 'Oscar Wilde' },
  { text: 'You only live once, but if you do it right, once is enough.', author: 'Mae West' },
  { text: 'In three words I can sum up everything I’ve learned about life: it goes on.', author: 'Robert Frost' },
  { text: 'If you tell the truth, you don’t have to remember anything.', author: 'Mark Twain' },
  { text: 'The man who does not read has no advantage over the man who cannot read.', author: 'Mark Twain' },
  { text: 'Without music, life would be a mistake.', author: 'Friedrich Nietzsche' },
  { text: 'We accept the love we think we deserve.', author: 'Stephen Chbosky' },
  { text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'Darkness cannot drive out darkness: only light can do that.', author: 'Martin Luther King Jr.' },
  { text: 'A friend is someone who knows all about you and still loves you.', author: 'Elbert Hubbard' },
  { text: 'To live is the rarest thing in the world. Most people exist, that is all.', author: 'Oscar Wilde' },
  { text: 'That which does not kill us makes us stronger.', author: 'Friedrich Nietzsche' },
  { text: 'Imperfection is beauty, madness is genius and it’s better to be absolutely ridiculous than absolutely boring.', author: 'Marilyn Monroe' },
  { text: 'And, when you want something, all the universe conspires in helping you to achieve it.', author: 'Paulo Coelho' },
  { text: 'It is better to be hated for what you are than to be loved for what you are not.', author: 'André Gide' },
  { text: 'The only thing we have to fear is fear itself.', author: 'Franklin D. Roosevelt' },
  { text: 'Courage is grace under pressure.', author: 'Ernest Hemingway' },
  { text: 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', author: 'Buddha' },
  { text: 'The journey of a thousand miles begins with one step.', author: 'Lao Tzu' },
  { text: 'That’s one small step for man, one giant leap for mankind.', author: 'Neil Armstrong' },
  { text: 'Genius is one percent inspiration and ninety-nine percent perspiration.', author: 'Thomas A. Edison' },
  { text: 'Float like a butterfly, sting like a bee.', author: 'Muhammad Ali' },
  { text: 'I came, I saw, I conquered.', author: 'Julius Caesar' },
  { text: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt' },
  { text: 'If you judge people, you have no time to love them.', author: 'Mother Teresa' },
  { text: 'My mission in life is not merely to survive, but to thrive.', author: 'Maya Angelou' },
  { text: 'I think therefore I am.', author: 'René Descartes' },
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
  { text: 'Wherever you go, go with all your heart.', author: 'Confucius' },
  { text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar' },
  { text: 'The good life is one inspired by love and guided by knowledge.', author: 'Bertrand Russell' },
  { text: 'Try to be a rainbow in someone’s cloud.', author: 'Maya Angelou' },
  { text: 'You do not find the happy life. You make it.', author: 'Camilla Eyring Kimball' },
  { text: 'Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.', author: 'Jamie Paolinetti' },
  { text: 'The only true wisdom is in knowing you know nothing.', author: 'Socrates' },
  { text: 'It is not length of life, but depth of life.', author: 'Ralph Waldo Emerson' },
  { text: 'Happiness depends upon ourselves.', author: 'Aristotle' },
  { text: 'May you live all the days of your life.', author: 'Jonathan Swift' },
  { text: 'Life itself is the most wonderful fairy tale.', author: 'Hans Christian Andersen' },
  { text: 'Do one thing every day that scares you.', author: 'Eleanor Roosevelt' },
  { text: 'Keep your face always toward the sunshine, and shadows will fall behind you.', author: 'Walt Whitman' },
  { text: 'You must be the change you wish to see in the world.', author: 'Mahatma Gandhi' },
  { text: 'The best revenge is massive success.', author: 'Frank Sinatra' },
  { text: 'An eye for an eye only ends up making the whole world blind.', author: 'Mahatma Gandhi' },
  { text: 'The most common way people give up their power is by thinking they don’t have any.', author: 'Alice Walker' },
  { text: 'The most difficult thing is the decision to act, the rest is merely tenacity.', author: 'Amelia Earhart' },
  { text: 'Every strike brings me closer to the next home run.', author: 'Babe Ruth' },
  { text: 'Definiteness of purpose is the starting point of all achievement.', author: 'W. Clement Stone' },
  { text: 'Life is 10% what happens to me and 90% of how I react to it.', author: 'Charles Swindoll' },
  { text: 'The most wasted of all days is one without laughter.', author: 'E. E. Cummings' },
  { text: 'You can never cross the ocean until you have the courage to lose sight of the shore.', author: 'Christopher Columbus' },
  { text: 'I’ve learned that people will forget what you said, but people will never forget how you made them feel.', author: 'Maya Angelou' },
  { text: 'Either you run the day, or the day runs you.', author: 'Jim Rohn' },
  { text: 'The mind is not a vessel to be filled, but a fire to be kindled.', author: 'Plutarch' },
  { text: 'Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.', author: 'Johann Wolfgang von Goethe' },
  { text: 'The two hardest tests on the spiritual road are the patience to wait for the right moment and the courage not to be disappointed with what we encounter.', author: 'Paulo Coelho' },
  { text: 'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', author: 'David Brinkley' },
  { text: 'No act of kindness, no matter how small, is ever wasted.', author: 'Aesop' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'The best way to predict the future is to create it.', author: 'Peter Drucker' },
  { text: 'Courage is resistance to fear, mastery of fear, not absence of fear.', author: 'Mark Twain' },
  { text: 'Only put off until tomorrow what you are willing to die having left undone.', author: 'Pablo Picasso' },
  { text: 'People often say that motivation doesn’t last. Well, neither does bathing — that’s why we recommend it daily.', author: 'Zig Ziglar' },
  { text: 'We must let go of the life we have planned, so as to accept the one that is waiting for us.', author: 'Joseph Campbell' },
  { text: 'And in the end, it’s not the years in your life that count. It’s the life in your years.', author: 'Abraham Lincoln' },
  { text: 'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do.', author: 'Mark Twain' },
  { text: 'Build your own dreams, or someone else will hire you to build theirs.', author: 'Farrah Gray' },
  { text: 'The battles that count aren’t the ones for gold medals. The struggles within yourself are the ones that matter.', author: 'Jesse Owens' },
  { text: 'Education is the most powerful weapon which you can use to change the world.', author: 'Nelson Mandela' },
  { text: 'Your talent is God’s gift to you. What you do with it is your gift back to God.', author: 'Leo Buscaglia' },
  { text: 'Change is the law of life. And those who look only to the past or present are certain to miss the future.', author: 'John F. Kennedy' },
  { text: 'I never dreamed about success, I worked for it.', author: 'Estée Lauder' },
  { text: 'Don’t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller' },
  { text: 'I find that the harder I work, the more luck I seem to have.', author: 'Thomas Jefferson' },
  { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau' },
  { text: 'If you really look closely, most overnight successes took a long time.', author: 'Steve Jobs' },
  { text: 'The road to success and the road to failure are almost exactly the same.', author: 'Colin R. Davis' },
  { text: 'Opportunities don’t happen. You create them.', author: 'Chris Grosser' },
  { text: 'Don’t be distracted by criticism. Remember — the only taste of success some people get is to take a bite out of you.', author: 'Zig Ziglar' },
  { text: 'Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier; wish you were better.', author: 'Jim Rohn' },
  { text: 'The function of leadership is to produce more leaders, not more followers.', author: 'Ralph Nader' },
  { text: 'There is only one way to avoid criticism: do nothing, say nothing, and be nothing.', author: 'Aristotle' },
  { text: 'If you want to make your dreams come true, the first thing you have to do is wake up.', author: 'J.M. Power' },
  { text: 'Great minds discuss ideas; average minds discuss events; small minds discuss people.', author: 'Eleanor Roosevelt' },
  { text: 'A goal properly set is halfway reached.', author: 'Zig Ziglar' },
  { text: 'You may be disappointed if you fail, but you are doomed if you don’t try.', author: 'Beverly Sills' },
  { text: 'Remember that not getting what you want is sometimes a wonderful stroke of luck.', author: 'Dalai Lama' },
  { text: 'You can’t fall if you don’t climb. But there’s no joy in living your whole life on the ground.', author: 'Unknown' },
  { text: 'We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.', author: 'Marie Curie' },
  { text: 'Too many of us are not living our dreams because we are living our fears.', author: 'Les Brown' },
  { text: 'Challenges are what make life interesting and overcoming them is what makes life meaningful.', author: 'Joshua J. Marine' },
  { text: 'If you want to achieve greatness stop asking for permission.', author: 'Unknown' },
  { text: 'Things work out best for those who make the best of how things work out.', author: 'John Wooden' },
  { text: 'To live a creative life, we must lose our fear of being wrong.', author: 'Joseph Chilton Pearce' },
  { text: 'If you are not willing to risk the usual you will have to settle for the ordinary.', author: 'Jim Rohn' },
  { text: 'Trust because you are willing to accept the risk, not because it’s safe or certain.', author: 'Unknown' },
  { text: 'Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea.', author: 'Swami Vivekananda' },
  { text: 'All our dreams can come true if we have the courage to pursue them.', author: 'Walt Disney' },
  { text: 'Good things come to people who wait, but better things come to those who go out and get them.', author: 'Unknown' },
  { text: 'If you do what you always did, you will get what you always got.', author: 'Anonymous' },
  { text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
  { text: 'Just when the caterpillar thought the world was ending, he turned into a butterfly.', author: 'Proverb' },
  { text: 'Successful entrepreneurs are givers and not takers of positive energy.', author: 'Anonymous' },
  { text: 'Whenever you see a successful business, someone once made a courageous decision.', author: 'Peter Drucker' },
  { text: 'Don’t let the fear of losing be greater than the excitement of winning.', author: 'Robert Kiyosaki' },
  { text: 'If you really want to do something, you’ll find a way. If you don’t, you’ll find an excuse.', author: 'Jim Rohn' },
  { text: 'The starting point of all achievement is desire.', author: 'Napoleon Hill' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier' },
  { text: 'If you want to fly, give up everything that weighs you down.', author: 'Buddha' },
];

export default quotes;
